### ISSUE TITLE
More Achievements reset unexpectedly.

### ISSUE THREAD

**Issue by DRY411S** [Bilka2/Achiever#3]
I have 2 desktop shortcuts to factorio. One uses a different mod-directory switch for when I want to play factorio in creative mode. The other shortcut uses the 'vanilla' mod-directory, which contains this mod.

If I start up factorio in 'creative' mod-directory it seems to have forgotten all this mod's achievements and begins adding them back when I achieve them. Then when I start factorio using the vanilla mod-directory, they again seem to be reset.

To be clear, the .exe, .\saves etc. are the same in each case, it's just the mod-directory that changes.

**Comment by Bilka2** [comment]
Not something this mod has any influence over. Make a bug report for the game if this issue is important to you and you can reproduce it.
